*** Variables ***

${GEOLOCATION_FEATURE_BTN_Android}          accessibility_id=test-GEO LOCATION
${GEOLOCATION_FEATURE_PAGE_Android}         accessibility_id=test-GEO LOCATION-SCREEN
${GEOLOCATION_LATITUDE}                     accessibility_id=test-latitude
${GEOLOCATION_LONGITUDE}                    accessibility_id=test-longitude
${GEOLOCATION_TEXT_1}                       Below you will find the latitude and longitude. You can use Appium to change them with this link.
${GEOLOCATION_TEXT_2}                       Determining the position on Android can take a while.